### ISSUE TITLE
Use Sass as default preprocessor?

### ISSUE THREAD

**Issue by nicolaisueper** [micromata/generator-baumeister#46]
I'd start moving the generator to v4 step by step. I was wondering if we should use Sass by default or add an option to choose between less and sass. How do you think about that @mischah?

**Comment by mischah** [comment]
I don’t see the need to have an option. Keep it simple.

So you can use Sass if we decide (hopefully monday) to merge micromata/bootstrap-kickstart#167 :shipit:
