### ISSUE TITLE
package-lock.json doesn't exist.

### ISSUE THREAD

**Issue by Chris2011** [micromata/generator-baumeister#49]
I tried to install the baumeister generator for the first time and I got this error:

![baumeister-problem](https://user-images.githubusercontent.com/795658/27264124-85553198-5478-11e7-9b6e-b1c1b1ce8e6f.png)

The problem is that the package-lock.json file doesn't exist in your generator template directory. I created the file by my own only to test it and it works. So maybe you should prevent to copy this file, because it is a auto generated file and will be not needed by the user, I think.

Regards

Chris

**Comment by mischah** [comment]
Ahh. Damn. it does exist in the Github Repo. But it seems that it’s not possible to publish a `package-lock.json` even if it’s not in the projects root directory. 

Thanks for the report. Going to fix this …

**Comment by mischah** [comment]
Version 1.0.1 is published on npm on should arrive in a matter of minutes.

**Comment by Chris2011** [comment]
Great, thx. :)
