### ISSUE TITLE
Does not work on macOS

### ISSUE THREAD

**Issue by derwaldgeist** [micromata/generator-baumeister#52]
I like the concept of this generator, but I can't get it working on macOS.

If I try to run `gulp --tasks`, this only results in an error message:

```
[13:33:56] Using gulpfile ~/Documents/Development/htdocs/tests/frontend-test/gulpfile.babel.js
(node:25679) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/Users/waldgeist/.nvm/versions/node/v8.6.0/lib/node_modules/gulp/lib/taskTree.js:4
  return Object.keys(tasks)
                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (/Users/waldgeist/.nvm/versions/node/v8.6.0/lib/node_modules/gulp/lib/taskTree.js:4:17)
    at logTasks (/Users/waldgeist/.nvm/versions/node/v8.6.0/lib/node_modules/gulp/bin/gulp.js:134:14)
    at /Users/waldgeist/.nvm/versions/node/v8.6.0/lib/node_modules/gulp/bin/gulp.js:127:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

Executing `gulp serve` results in:

```
[13:34:59] Using gulpfile ~/Documents/Development/htdocs/tests/frontend-test/gulpfile.babel.js
(node:25691) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/Users/waldgeist/.nvm/versions/node/v8.6.0/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/waldgeist/.nvm/versions/node/v8.6.0/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

I've tried Node 8.6.0, Node 7.4.0, and Node 6.11.4. I guess the Babel transformations and imports don't work properly.

**Comment by derwaldgeist** [comment]
Update: `yarn start` works, but not with a globally installed gulp.

My Gulp version info:
CLI version 3.9.1
Local version 4.0.0-alpha.2

**Comment by Anbe93** [comment]
Hey @derwaldgeist,
did you install yeoman globally?

**Comment by nicolaisueper** [comment]
@derwaldgeist Please try the following:

```
$ npm rm gulp -g
$ npm rm gulp-cli -g
$ npm cache clean

# Install the latest Gulp CLI Tools from Github  globally
$ npm install gulpjs/gulp-cli -g
$ cd <project-root> && gulp
```

**Comment by nicolaisueper** [comment]
This could be an issue, if this isn't documented anywhere.

**Comment by mischah** [comment]
Hej @derwaldgeist As @nicolaisueper already mentioned, You need the new Gulp CLI.

But you can install it via the npm registry.
See: https://www.npmjs.com/package/gulp-cli

Current version is 1.4.0 so `gulp -v` should return the following after successful installallation:

```
$ gulp -v
[10:19:04] CLI version 1.4.0
```

Feel free to reopen, if you still encounter problems.

**Comment by derwaldgeist** [comment]
Ok, thanks for the info. It wasn't obvious from the readme that you need the very latest gulp version. I didn't even know that there's a difference between `gulp` and `gulp-cli`. So I assumed that my `gulp` version would work, as it was the latest I got from npm via `npm install -g gulp`.

**Comment by mischah** [comment]
@derwaldgeist 

Thanks for your Feedback 👍 

Would this [PR](https://github.com/micromata/generator-baumeister/pull/53/files) make sense to you?
